### ISSUE TITLE
Port to CMT rather than Synaptics

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#10]
Review /platform/xorg-conf/50-touchpad-cmt-overlay.conf

**Comment by arnoldthebat** [comment]
https://chromium.googlesource.com/chromiumos/platform/xorg-conf/+/master/20-mouse.conf
https://chromium.googlesource.com/chromiumos/platform/xorg-conf/+/master/40-touchpad-cmt.conf

**Comment by arnoldthebat** [comment]
https://chromium.googlesource.com/chromiumos/platform/xorg-conf/+/factory-4455.B/50-touchpad-synaptics.conf

**Comment by arnoldthebat** [comment]
Sample:

# Configure touchpads to use xf86-input-synaptics X input driver
Section "InputClass"
    Identifier "touchpad"
    MatchIsTouchpad "on"
    MatchDevicePath "/dev/input/event*"
    Driver     "synaptics"
    Option     "MinSpeed" "0.4"
    Option     "MaxSpeed" "1.0"
    Option     "AccelFactor" "0.0035"
    Option     "HorizScrollDelta" "6"
    Option     "VertScrollDelta" "18"
    Option     "HorizEdgeScroll" "0"
    Option     "VertEdgeScroll" "0"
    Option     "TapButton1" "1"
    Option     "TapButton2" "3"
    Option     "TapButton3" "2"
    Option     "MaxTapTime" "180"
    Option     "FingerLow" "40"
    Option     "FingerHigh" "43"
    Option     "EmulateTwoFingerMinZ" "32"
    Option     "VertTwoFingerScroll" "1"
    # Horizontal scrolling is disabled for now as it interferes w/ vertical.
    Option     "HorizTwoFingerScroll" "0"
    # The resolutions were balanced for the Dell Latitudes
    Option     "HorizResolution" "75"
    Option     "VertResolution" "108"
EndSection

**Comment by mpipo** [comment]
Hey Arnold,

Is it possible to make tap-to-click work on a Mac using Synaptics? Tried digging around, can't find anything. Changing xorg.conf.d stuffs results in Xorg crashing.

**Comment by arnoldthebat** [comment]
Hi

Have you looked at https://bbs.archlinux.org/viewtopic.php?id=121153

**Comment by mpipo** [comment]
Thanks! It's working now (except for a small delay after tapping) without crashing.

Don't know why that didn't work before.

**Comment by arnoldthebat** [comment]
Not relevant anymore
