### ISSUE TITLE
Enable nvme support in kernel

### ISSUE THREAD

**Issue by dz0ny** [arnoldthebat/chromiumos#100]
See https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-reviews/_X8rXJnPCH8

**Comment by arnoldthebat** [comment]
Needs +CONFIG_BLK_DEV_NVME adding.

**Comment by dz0ny** [comment]
In the latest "special build" the kernel already has support for NVME. This was not the case 2 years ago :)

**Comment by arnoldthebat** [comment]
Awesome. I was simply going to check but didnt have time last night. Consider this closed therefore
