### ISSUE TITLE
Marvell Avastar 350N wifi chip not working

### ISSUE THREAD

**Issue by kekx** [arnoldthebat/chromiumos#102]
Booted up the newest ChromiumOS special build (R55 as of now) on my Surface Pro 2 and was stopped by unsupported wifi.
I don't know about ChromiumOS but in general Linux, this chip has stock kernel support and it's handled by the mwifiex_usb module, if that helps.

**Comment by arnoldthebat** [comment]
Add all libertas

**Comment by arnoldthebat** [comment]
Will be enabled in R65
