### ISSUE TITLE
trackpoint support

### ISSUE THREAD

**Issue by huiyiqun** [arnoldthebat/chromiumos#103]
I have a Thinkpad E431 and boot chromium os from usb with your special build. Everything works well except scrolling with the trackpoint.

However, there is already [trackpoint support](https://bugs.chromium.org/p/chromium/issues/detail?id=430319) in chromium os since 6680.11.0. 

I'm not sure whether it's because E431 has the middle buttom embedded in the touchpad.

**Comment by arnoldthebat** [comment]
Try in the R64 special. Better touchpad support is available
