### ISSUE TITLE
"BUILD – R55-8777" Install Problem...

### ISSUE THREAD

**Issue by batuhangoksu** [arnoldthebat/chromiumos#104]
My computer’s model is “x”. I have downloaded the “BUILD – R55-8777” file to my USB drive and I restart my computer from UEFI. 

Then let me explain you what I have faced. 
1.	The Google Crome logo shows up, but after a while the screen becomes black. 
2.	After a while when i press to “CTRL+ALT+F2” the terminal screen shows up. 
3.	I start the installation with the following commands: “login - sudo su - chromeos-install --dst /dev/sda”
4.	After the installation finishes the i reboot the computer.
5.	While rebooting the computer I eject the USB drive. 

When the computer starts up, again the Google Chrome logo shows up and disappears, when pressing to CTRL+ALT+F2 the terminal screen shows up like the installation has not been done. 

How can I solve this issue? 

Laptop Model: http://www8.hp.com/tr/tr/products/laptops/product-detail.html?oid=13403343#!tab=specs

**Comment by haxalicious** [comment]
You may have secure boot enabled. I don't know if it can boot with it enabled, try disabling it and seeing if that helps. You should also make sure you are using the 64-bit (amd64) version and not the 32-bit (i386) version, UEFI won't boot 32-bit oses.

**Comment by arnoldthebat** [comment]
Ancient version. Please try again on R64
