### ISSUE TITLE
Acer Cloudbook 14 hangs on build Camd64OS_R55-8777.0-Special

### ISSUE THREAD

**Issue by ksemerick** [arnoldthebat/chromiumos#105]
When using Camd64OS_R55-8777.0-Special builds, the unit hangs on booting, showing the chromium boot screen, then goes into a loop between a few Ascii screens. It boots fine on the vanilla build, but with the no trackpad or audio support. Same situation with corresponding Cx86 builds. Any suggestions? Thanks.

**Comment by arnoldthebat** [comment]
Should work on later versions
