### ISSUE TITLE
Realtek RTL8188EE doesn't work

### ISSUE THREAD

**Issue by tainanngabriel** [arnoldthebat/chromiumos#107]
Please fix it, I really want to use ChromiumOS! :D Thx

**Comment by tuananh88c25** [comment]
You can install CloudReady to use ChromiumOS
My wifi is RTL8188EE too

**Comment by Gilbert32** [comment]
Same here. RTL8188EE and not working

**Comment by arnoldthebat** [comment]
Should be fixed in version R64
