### ISSUE TITLE
sis190 drivers missing from kernel

### ISSUE THREAD

**Issue by montvid** [arnoldthebat/chromiumos#108]
Thank you for creating this useful distribution! I would like to ask you to compile the sis190 ethernet drivers with it because my Asus X50SL can't use the wired Internet. I checked your distribution and the SIS drivers are missing - the kernel.org kernel has them. Or maybe someone could inform me how to add the driver myself? Thank you. Everything else seems to work out of the box! The Neverware distro has the same problem unfortunately.

Lubuntu 16.04 64bit is running fine with these drivers:
00:04.0 Ethernet controller: Silicon Integrated Systems [SiS] 191 Gigabit Ethernet Adapter (rev 02)
/sys/bus/pci/drivers/sis190/0000:00:04.0

**Comment by arnoldthebat** [comment]
In kernel tree - just needs switching on!

**Comment by arnoldthebat** [comment]
Will be enabled in R65
