### ISSUE TITLE
HID_SENSOR_HUB module

### ISSUE THREAD

**Issue by ghost** [arnoldthebat/chromiumos#110]
Hello,

There is no HID_SENSOR_HUB so we are unable to have event from accelorometer like this : 0483:91d1 STMicroelectronics

**Comment by mattvoss** [comment]
It would be nice to get this module. I have the Dell 7140 Venue Pro and auto-rotation doesn't work because this module is missing.

**Comment by NeoMatrixJR** [comment]
+1

**Comment by arnoldthebat** [comment]
Apologies - this will be in the next Alpha build...
