### ISSUE TITLE
RTL8192E Not Working

### ISSUE THREAD

**Issue by javakrypt** [arnoldthebat/chromiumos#111]
Hi,

I've tried looking around for drivers for this card, and all I'm seeing is "it's support" - even from most mainstream linux builds - which is true. I ran ElementaryOS which supported this WLAN card natively with it being based off Ubuntu. 

But with chromium it's nothing but people saying they can't get it working. What's weird is the RTL8192SE drivers are working, but not the RTL8192E ones.

Is there going to be an update to fix this issue? :( This also occurs in the CloudReady version of ChromeOS.

**Comment by arnoldthebat** [comment]
'Should' now be fixed in R64 special build. Can you test please?
