### ISSUE TITLE
Single Sign-On issue related to G-Suite for Education users tied to Microsoft Active Directory

### ISSUE THREAD

**Issue by GreenDTC** [arnoldthebat/chromiumos#112]
We use Google Single Sign-On with Google's G-Suite for Education which synchronizes our users accounts between Google and Microsoft's Active Directory for both our staff and students.  When a Single Sign-On user tries to login a blank white box opens and prevents the user from logging in to the ChromiumOS Device.  If the user logs in to the ChromiumOS as guest mode and tries to login to anything Google related a blank browser window opens and prevents the user from going any farther.  The users receive the same blank browser window if they try to login to the Web Mail Portal at "https://login.microsoftonline.com/".  If I use a non Single-Sign-On account I can login and get everything except the microsoft webmail.  We are comparing this version of ChromiumOS with the CloudReady product provided by Neverware.  Cloudready allows the logins, but as of yet this version of ChromiumOS does not.  Not sure where to even start to resolve this.  We are using Cx86OS_R55-8777.0-Special as our deployment version.  I will try another version and see if it has the same issue.  Is this related to the ChromiumOS build, a missing plugin, or something else?  Any help or suggestions are appreciated.

**Comment by arnoldthebat** [comment]
Did you get anywhere with later versions?

**Comment by arnoldthebat** [comment]
Too old and no response. Closing off. Feel free to reopen if this is still an issue
