### ISSUE TITLE
Dell Lattitude D830 won't boot

### ISSUE THREAD

**Issue by jsajczuk** [arnoldthebat/chromiumos#115]
have tried various "special" versions of ChromiumOS and had the same results. laptop stops at "booting the kernel".  

specs can be found at: https://www.cnet.com/products/dell-latitude-d830/specs/ 

tried the daily version Camd64OS-20170223020202.img...... boots thru white Chromium screen then goes to a dull grey screen that blinks to black and back.

**Comment by arnoldthebat** [comment]
Should be sorted in the latest alpha builds. Please retest.
