### ISSUE TITLE
Intel Centrino Advanced-N 6205 shows as "No Networks"

### ISSUE THREAD

**Issue by gsora** [arnoldthebat/chromiumos#116]
As the title says.

I'm using the 20170326 build.

iwlwifi is loaded, firmware is present in /lib/firmware, but I can't get this thing to digest my wireless card.

It was working fine with 4x ChromiumOS builds.

**Comment by arnoldthebat** [comment]
This is working in the latest special builds. Daily builds dont have the FW built in.
