### ISSUE TITLE
Vanilla and special builds doesn’t works with Hyper‑V

### ISSUE THREAD

**Issue by ytrezq** [arnoldthebat/chromiumos#117]
Since Windows 8 and server 2012 Hyper‑V allows using ᴜᴇꜰɪ provided the hard drive is emulated under an ꜱᴄꜱɪ controller.
After disabling verified ᴜᴇꜰɪ booting, everything hangs at his stage :
![](https://lh3.googleusercontent.com/-Q9x8EQOEahk/WOAuuAxsoSI/AAAAAAAAABI/80Bhxuwh2QgOmkZKHHO7VDrDRm5IDo04QCLcB/s1600/Image%2B1.bmp)

**Comment by arnoldthebat** [comment]
Sorry. I wont support hyper-v.
