### ISSUE TITLE
Samsung R730 Fails to Render Screen

### ISSUE THREAD

**Issue by ilyaigpetrov** [arnoldthebat/chromiumos#119]
`Camd64OS_R57-9202.B-Vanilla` boots, I hear booting sounds, it reacts to Ctrl+Alt+Z (assistive tools), virtual terminals work fine, but on VT1 (F1) nothing is displayed or some garbage is displayed.

Graphic card is NVIDIA GeForce 310M.

[dmesg.txt](https://github.com/arnoldthebat/chromiumos/files/910837/dmesg.txt)
[chrome_20170410-090730.txt](https://github.com/arnoldthebat/chromiumos/files/910840/chrome_20170410-090730.txt)
[messages.txt](https://github.com/arnoldthebat/chromiumos/files/910836/messages.txt)

**Comment by arnoldthebat** [comment]
Try again with the R64 special build please
