### ISSUE TITLE
Out of date Chrome results in ERR_CERTIFICATE_TRANSPARENCY_REQUIRED ssl error on sites

### ISSUE THREAD

**Issue by Mbd06b** [arnoldthebat/chromiumos#122]
Version 54.0.2845.0 (64-bit)
Platform 8659.0.2016_08_07_1252 (Developer Build -tonyd) developer-build amd64-atb

Channel: Stable Build //issue affects all channels (stable, beta, and dev). 

We were trying to run a web application, and are subject to this known Chromium Issue, regarding security Certs (not just Symantec).  see here for clear details on the type of problem known to affect versions 53 and 54.
https://bugs.chromium.org/p/chromium/issues/detail?id=664177

Blog notice related to the issue from Google:
https://security.googleblog.com/2015/10/sustaining-digital-certificate-security.html

A set of certificates (_I'm not sure if these are the ones affected, or updated_):
https://chromium.googlesource.com/chromium/src/+/master/net/data/ssl/symantec

Is it possible to expedite the OTA, version 55 update for this build? 
A workaround (note https load errors persist through "proceed anyway" prompt)?
Or prioritize the fix? This issue affects many legitimate websites, including some big ones like amazon.com.

**Comment by arnoldthebat** [comment]
This is foxed in later versions. Try a new install manually, or if you can wait a week or so, the update servers will be back online.
