### ISSUE TITLE
Realtek 8723BE is not detected

### ISSUE THREAD

**Issue by ghost** [arnoldthebat/chromiumos#123]
I tried latest Enhanced Vanilla and Special Build, it doesn't working BUT it's working on older special edition

**Comment by gdcrocx** [comment]
First of all, Great job! Secondly, facing the same issue with the latest build of daily and special builds. Unable to use Wifi on Acer One 14. Require **rtl8723b**  support driver for these Acer series notebooks. Please suggest what could be done, happy to support or work along. Thanks.

**Comment by arnoldthebat** [comment]
Should be fixed in latest R64 versions.
