### ISSUE TITLE
Synaptics touchpad not working

### ISSUE THREAD

**Issue by Syfher** [arnoldthebat/chromiumos#125]
The touchpad is only working with very limited functionality (no two finger scrolling etc.). 

Tried with the link: https://arnoldthebat.co.uk/wordpress/2013/01/08/how-to-get-the-touch-pad-working-in-chromium-os/  but it's not working for me. 

The configuration file is found here on my install: /etc/gesture/40-touchpad-cmt.conf

**Comment by arnoldthebat** [comment]
Should be fixed in the latest special build. Ive tested on my synaptic and two finger scrolling works..

Its a bit jittery but workable
