### ISSUE TITLE
No install on HP Compaq dc7800/7900 SFF PC

### ISSUE THREAD

**Issue by tbrownwlocks** [arnoldthebat/chromiumos#127]
Created the boot USB (32-bit and 64-bit; seperate usb sticks) and ran it on an HP Compaq dc8100 SFF with no issue, but when directing 7800/7900 to boot from USB device it hangs on a dark screen for 1 second and then goes into booting into Windows (was planning on wiping the HDD during the USB boot process).

Not sure if its a graphics driver or what, but I can't get past this step. 

Any help would be appreciated.

**Comment by arnoldthebat** [comment]
Try the latest alpha builds please. Hopefully fixed. Reopen this bug if not.
