### ISSUE TITLE
Doesn't boot on a Macbook Pro 10,1 (Early 2013)

### ISSUE THREAD

**Issue by Armored-Dragon** [arnoldthebat/chromiumos#133]
When I try booting it from a flash drive, a GRUB menu appears. Booting from `local image A` brings me to the Chromium boot splash. It stays there for a minute or two, but then suddenly goes to a black screen. The computer stays on, but there are no disk read/writes, and the screen stays off - even the backlight. It doesn't respond to any input.

I'm using Special build R60-9592.B. The laptop has a GT 650M and 3rd generation Core i7. I've tried multiple builds of Chromium OS. CloudReady just sticks on a black screen with white pixels on the top before becoming pure black. Flint OS does the same thing as these ArnoldTheBat builds, but with a Flint OS boot splash instead.

Any help would be appreciated.

**Comment by Armored-Dragon** [comment]
Update: the CPU is a i7-3740QM, and GPU is actually a GT 630M **Mac Edition**.

I've tried using rEFInd to spoof the OS as Mac so the firmware doesn't hide the integrated GPU from Chromium OS, but that doesn't even help. I've tried rEFInd spoofing for all 3 builds too... none of them start working. However, these builds were able to show the Chromium OS cursor for a split second before the screen turned off.

**Comment by Armored-Dragon** [comment]
I've been able to get it working... mostly. The VT, frecon, works. I found a script called [gpu-switch](https://github.com/0xbb/gpu-switch) which is able to switch the GPU to integrated for next boot. After running that (in Flint OS), next boot the Chromium UI works. However, the script doesn't work on these builds because the kernel isn't built with `efivarfs` enabled. The kconfig option is `CONFIG_EFIVAR_FS` - could you please enable it? @arnoldthebat 

It would also be nice if there was a note on the website about this, or even better, have the script built in. It's licensed under the MIT license. 

I'd also like to be able to use the discrete GPU in Chromium OS. With the discrete GPU, frecon works, but not Chromium itself. The screen is completely off (including the backlight). Any ideas?

**Comment by arnoldthebat** [comment]
CONFIG_EFIVAR_FS will be enabled in the next build...
