### ISSUE TITLE
HP G62 

### ISSUE THREAD

**Issue by Donenz** [arnoldthebat/chromiumos#134]
Rolling out alot of builds at the moment with no issues.... Except... i have around 20 HP G62's
All acting the same way when i try the install. As soon as i get to the log on as Chronos, the unit just shut down?
Any ideas? 
I have tried bios settings, updates etc... no joy
Help needed badly!! :)

**Comment by Donenz** [comment]
Update- I have now tried different build, x64, amd and ard.... no joy..
all have the same effect... all working until the i try to install locally, then it just shuts down.

@arnoldthebat Any ideas?

**Comment by arnoldthebat** [comment]
None - closing this since  its ancient
