### ISSUE TITLE
Google Play store is not opening

### ISSUE THREAD

**Issue by ghost** [arnoldthebat/chromiumos#140]
CHROMIUMOS ENHANCED SPECIAL BUILD – R62-9901.B has a problem with google play store, Google play store is not opening

**Comment by NexusX44** [comment]
Have same problem on Dell XPS 15 9550, prompted to sign out and update over and over again

**Comment by DEaton66** [comment]
Have same problem on Dell Latitude E6540, prompted to sign out and update over and over again

**Comment by arnoldthebat** [comment]
It wont work yet. Detail https://arnoldthebat.co.uk/wordpress/2017/08/28/chromiumos-enhanced-special-build-r60-9592-b/

**Comment by arnoldthebat** [comment]
Duplicate of #179
