### ISSUE TITLE
Boot from USB Problem Acer Aspire 5742G

### ISSUE THREAD

**Issue by giov18** [arnoldthebat/chromiumos#146]
Hi!
When I try to boot from the USB that I created my laptop shows a black screen for a second, then the chromium logo then it enters a very broken, glitchy interface. tried the USB stick on other laptops and it worked, so the USB is not the problem. I've read on some website that it may be a graphics card incompatibility (nVidia GT 540m).
Here are the specs:
Aspire 5742G-384G50Mnkk
15.6'' (1366 x 768) 
Core i3 380M 2.53GHz 
4GB RAM
500GB 
nVidia GeForce GT 540M 2GB

![461546fd-6ac0-48a4-9c2a-8449dda84faa](https://user-images.githubusercontent.com/36040472/35688564-20499a7c-077a-11e8-9f59-b34d97fac311.jpeg)
![6872d9d2-b6b3-4b02-970e-95dbe4eefc8d](https://user-images.githubusercontent.com/36040472/35688565-206cbed0-077a-11e8-9e01-b284a13cfa46.jpeg)
![fa5212ef-428a-41b2-91e6-96c2d4d42d0d](https://user-images.githubusercontent.com/36040472/35688566-2088406a-077a-11e8-9c3b-0221161cd0a7.jpeg)
![f7f2967b-8808-4e4e-b3c0-267d546205c7](https://user-images.githubusercontent.com/36040472/35688567-20a87308-077a-11e8-92ed-bc5875efc23d.jpeg)
![1b3878a4-f9bd-4016-9cf2-130fdd990805](https://user-images.githubusercontent.com/36040472/35688568-20c92328-077a-11e8-8671-69b7a60e2429.jpeg)
![4d3705c8-7619-4b5d-9f96-51b5398cfa31](https://user-images.githubusercontent.com/36040472/35688569-20e7bb08-077a-11e8-9f81-26a1c0a79f64.jpeg)

**Comment by arnoldthebat** [comment]
Try again with the R64 special build please
