### ISSUE TITLE
Dell Optiplex 755 - Builds since 60

### ISSUE THREAD

**Issue by agvonline** [arnoldthebat/chromiumos#152]
Builds 62 and 64 don't install to Dell OptiPlex 755 (Intel E6550 Dual Core) with integrated graphics. Tried a few builds, vanilla and special. Some reboot after ChromeOS splash screen. Some stuck on black screen. 
Build 60 works, as does 56.
Any thoughts?

**Comment by arnoldthebat** [comment]
It could be the 4.14 kernel breaking graphics support. Could you give the dailies a quick test and let me know?

**Comment by agvonline** [comment]
Just tried with today's (03/04) and it still black-screens. Your help/thoughts is much appreciated as we have a lot of these machines that we use Chromium (pre v62) on, and can't upgrade.

**Comment by arnoldthebat** [comment]
This 'should' be OK in later builds. Can you retest please?
