### ISSUE TITLE
WIFI is not showing

### ISSUE THREAD

**Issue by pranjalmalkhede** [arnoldthebat/chromiumos#154]
I am using a amd64R64 build on asus r558uq laptop. whenever I start wifi it gets disabled automaticallly. 
No network is showing.

**Comment by arnoldthebat** [comment]
You mean this? https://www.asus.com/in/Laptops/ASUS-VivoBook-R558UQ/specifications/

Can you post the output of lspci and lsusb please?

**Comment by arnoldthebat** [comment]
Could be lack of ATH9k.

Check https://cateee.net/lkddb/web-lkddb/ATH9K.html re NE186H stack dependant on feedback.

**Comment by arnoldthebat** [comment]
Should be baked into R71 when released
