### ISSUE TITLE
Stateful Update 404

### ISSUE THREAD

**Issue by Sweets** [arnoldthebat/chromiumos#155]
404 on http://chromebld.arnoldthebat.co.uk:9080/static/stateful.tgz (shown when running `stateful_update`).

As an aside, wget is no longer used on Chromium OS, so I figured this out when trying to manually do a stateful update with curl.

**Comment by brandonhygate** [comment]
Any movement on this? I got an ERR_CONNECTION_REFUSED at http://chromebld.arnoldthebat.co.uk:9081/static/stateful.tgz

**Comment by arnoldthebat** [comment]
Update servers are currently down. Ill check when they are running (likely in the next few weeks)

**Comment by arnoldthebat** [comment]
Was due to servers being offline. Now working.
