### ISSUE TITLE
ARM 64 bit

### ISSUE THREAD

**Issue by tuxether** [arnoldthebat/chromiumos#156]
Do the ARM builds work for aarch64? I'm getting a blank screen on my chromebook.

**Comment by XaeroVincent** [comment]
I think the builds are made automatically by a build bot and are pretty much untested?

In addition to having official Chrome OS running on a non-chromebook PC, I also have an ARM Rockchip-based Chromebook. The ARM chromebooks appear to require specialized patch kernels to handle those SoC's GPUs.

Maybe try replacing Arnoldthebat's ARM ChromiumOS build kernel with the official one designed for your Chromebook? You'll want to fetch vmlinuz.A & B from the 12th / EFI partition, /lib/firmware and /lib/modules/(kernel folder) from the root partition then copy them over to Arnold's image. Be sure to retain symbolic links and permissions when copying that stuff or else things will break.

**Comment by tuxether** [comment]
> Why do you want to run Chromium OS on an official Chromebook?

Open source, better privacy, running off USB, etc.

> The ARM Chromebooks appear to require specialized out-of-tree patched 3.x kernels to handle those SoCs and their OpenGL ES enabled GPUs. Maybe try replacing Arnoldthebat's ARM Chromium OS build kernel with the official one designed for your Chromebook found in the official Chrome OS install?

Hmm, you're right. The ChromiumOS kernel seems to lag behind the mainline kernel, so it didn't have the patches needed for my device. Copying the kernel files seems to fix the issue. For future reference, the device I have is [kevin](https://archlinuxarm.org/platforms/armv8/rockchip/samsung-chromebook-plus).

**Comment by hacker1024** [comment]
I want to emulate Chromium OS with QEMU/KVM on my phone. Are the ARM builds 64 or 32 bit?

**Comment by DUOLabs333** [comment]
@hacker1024 They seem to be 32 bit -- I use `qemu-system-aarch64` at it wouldn't boot.
