### ISSUE TITLE
Qualcomm Atheros QCA9377 card-driver issue

### ISSUE THREAD

**Issue by Wpark2547** [arnoldthebat/chromiumos#157]
My laptop has 8GB RAM, 1TB HDD and a 128GB SSD (Chromium installed on 1TB HDD, the SSD with Windows 10), Samsung Stock UEFI motherboard, Intel Pentium 3825U @1.90 GHz, and a Qualcomm Atheros QCA9377 Wi-Fi card but the Wi-Fi wont work. The OS itself boots just fine, but I can't set it up due to the Wi-Fi being disabled automatically when turning it on. What shall I do?

**Comment by arnoldthebat** [comment]
Ill see if I can build that in to later builds, if I can find a driver... In many cases however, its simpler just to buy an Intel WiFi card.

**Comment by sms-system** [comment]
I have the same problem. But in CloudReady this card works. It needs ath10k driver, which is missing #160

**Comment by dnim0ecaep** [comment]
Hi Arnold,
What can we do to entice you to get this working? I would become a patreon member and pay for such a fix.  Flintos, cloudready, and fydeos do this.  Thank you for the work you are doing.  For me, I’m 99% where I want to be.  If I install the asuka image, I can get android apps.

**Comment by vitakras** [comment]
I am having the same issue with Qualcomm Atheros QCA6174. The kernal module was set to `wl` and no kernal driver was set when i ran the `lspci -k` command. I also noticed that chromiumos had a ath10k folder in `lib/firmware` but I wasn't able to figure out how to load the driver.

**Comment by cicciocanestro** [comment]
I have also this problem

**Comment by arnoldthebat** [comment]
Can you try this again please. This should be sorted now
