### ISSUE TITLE
Make smaller img files

### ISSUE THREAD

**Issue by wodim** [arnoldthebat/chromiumos#159]
Given that like 80% of the .img file is zeroes, I'm sure there's something that can be done to make the .img files smaller so they fit in an 8G drive.

**Comment by arnoldthebat** [comment]
If I go for the default, errors are presented to users who use the OS permanently from USB. Im not going to reintroduce that, when you can get a USB3 16GB stick for £7

I could look to alter the partitioning, buts its low priority...

**Comment by arnoldthebat** [comment]
Closing since Im not altering this
