### ISSUE TITLE
Can I install chromiumos build onto my chromebook without wiping stateful partition?

### ISSUE THREAD

**Issue by ccaapton** [arnoldthebat/chromiumos#162]
Hi. I've a acer c720 chromebook in developer mode, and I would like to try some chromiumos build on it, like your build or some image from google's [buildbot](https://storage.cloud.google.com/chromeos-image-archive/amd64-generic-full/R68-10601.0.0-b2497379/index.html). Is it possible to use the built-in update-engine to complete the update, without using usb drive and wipe my stateful data?

I know chromeos only trust upstream servers which have the corresponding private key of "/usr/share/update_engine/update-payload-key.pub.pem", but as I have root capability, I can change that file, or bind-mount another file onto it during the updating process. Any other thing that will stop auto updating into your build?

**Comment by arnoldthebat** [comment]
No idea, sorry!
