### ISSUE TITLE
Legacy booting from USB just drops me into a Grub 2 Console

### ISSUE THREAD

**Issue by allsey87** [arnoldthebat/chromiumos#167]
Not sure exactly what is happening here since I was under the impression that booting in legacy mode should use syslinux. I confirmed this by attaching my USB stick with the latest (April 8th 2018) images to a virtualbox instance and noted that both bootloaders work as expected and were selected depending on whether I enabled/disabled EFI booting in the virtual box instance.

However, this is what I can see when I boot from my USB using my laptop (where I want to install ChromeOS). My laptop does not support any EFI booting etc:

![image](https://user-images.githubusercontent.com/3796345/40017183-eae385d4-57b8-11e8-8526-826cc32ce7dd.jpg)

Does anyone know the correct command to initiate the boot sequence from this point?

**Comment by arnoldthebat** [comment]
Im not seeing this on any of the builds to date. Can you try a later build please?
