### ISSUE TITLE
RLT8723AU wifi does not work

### ISSUE THREAD

**Issue by Rogue136198** [arnoldthebat/chromiumos#169]
I just tried build R65-10323.B and the Realtek RLT8723AU in my lenovo yoga 11s does not work. Any chance this can be looked into for the next release?

**Comment by arnoldthebat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix List](https://trello.com/c/vut7psOm/40-fix-list)

**Comment by arnoldthebat** [comment]
Should be fixed in R71
