### ISSUE TITLE
BCM4313 Not working

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#17]
http://arnoldthebat.co.uk/wordpress/2013/02/24/how-to-get-the-broadcom-wireless-drivers-working/comment-page-2/#comment-56119

https://gist.github.com/anonymous/d8a8af0a39e30281b06f

**Comment by RichardBronosky** [comment]
So does this explain why I put Camd64OS_R62-9901.B-Vanilla.7z onto a USB 3.0 stick with Etcher and was able to get it to boot but couldn't get past the obligatory adding of networks?

Is there a way to just get to a terminal?

**Comment by arnoldthebat** [comment]
Possibly. Terminal can be accessed via Ctrl-Alt-F2

**Comment by arnoldthebat** [comment]
Marking as wontfix. Its less hassle to go and buy an intel WIFI card! Even gentoo have deprecated BCM cards
