### ISSUE TITLE
Linux Kernel > 4.4 is not working good!

### ISSUE THREAD

**Issue by volram** [arnoldthebat/chromiumos#182]
There is a plethora of issues with kernels after 4.4. The system crash (i915 problems); cras (chrome os audio server) lock or block everything; no acpi battery (macbook pro) etc. None of this problems is present in Cloudready. So, I guess, the root of the problem is in the moment of the making of the kernels configuration (acpi options and the likes). Arnold, could you please look at this for next Special edition. Thank You.

**Comment by arnoldthebat** [comment]
Hi @volram . Yep, Ill review and thanks for the feedback.

**Comment by arnoldthebat** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix List](https://trello.com/c/vut7psOm/40-fix-list)

**Comment by arnoldthebat** [comment]
We are on 4.14 know so not relevent - closing.
