### ISSUE TITLE
RTL8192E isn't detected 

### ISSUE THREAD

**Issue by JustForgotMyName** [arnoldthebat/chromiumos#184]
Hi, i've tried the Chromium OS X86 and found ,that the RTL8192E  Wifi adapters wasn't detected.
i saw a page that said the R64 version has fixed the problem. but i can't install the R64 version because my device doesn't support 64 bit processor. any version from X86 that support RTL8192E wifi adapter??? if no i really hope the next update for X86 version would support RTL8192E wifi adapter

anyway thank you @arnoldthebat for your efforts of this project. i'm glad to see my old netbook rise n shine again. but i really hope you could make a fix for my problem ;)

**Comment by arnoldthebat** [comment]
Can you test this agian in R71 please?

**Comment by JustForgotMyName** [comment]
> Can you test this agian in R71 please?

any version of R71 that's x86??
