### ISSUE TITLE
Widevine Support

### ISSUE THREAD

**Issue by GitGerby** [arnoldthebat/chromiumos#186]
No widevine content decryption module support on SPECIAL BUILD – R67-10575.B; can you please add?  This would allow Netflix and Amazon Prime video usage.

**Comment by nphyx** [comment]
Same issue on current special build (Camd64OS_R67-10575.B-Vanilla) as of this post.

Netflix reports the plugin is not loaded. The page `chrome://plugins` does not exist, and "chrome://components" doesn't list anything that looks like widevine / cdm.

I tried dropping fresh builds of widevinecdm.so into `/usr/lib64/chromium/`, one from CloudReady and one built for Arch/Manjoro's chromium package, no luck with either.  It was a longshot anyway :( Original builds from this distribution were in there prior to the change.

CloudReady's bootable USB seems to work with widevine, but I couldn't get it to install to HDD so I switched to this build (which installed fine, just missing the proprietary plugins).

Bumping this in the meanwhile. Please let me know if you need more info.

**Comment by arnoldthebat** [comment]
Ive applied to be allowed to distribute it since its a closed source binary. If they permit it, Ill distribute, otherwise Im not allowed (sorry)

**Comment by nphyx** [comment]
Thanks for getting back - side question, if they don't allow you to distribute it, is there any way to successfully manually download it? If so, is this something we could make into a shell or python script? I've seen it done in out-of-date distributions of chromium elsewhere but it seems like the download URL is no longer valid.

**Comment by arnoldthebat** [comment]
Try this: https://packages.gentoo.org/useflags/widevine
Should hopefully give some pointers

**Comment by GitGerby** [comment]
Thank you!  Appreciate all your hard work on this project.

**Comment by jimbobstanton** [comment]
Sorry for the noob question here but I'm not clear what to do with the above info... The gentoo USE flag article makes me think that a flag needs to be set when compiling Chromium however the chrome-binary-plugins code simply downloads the .so file and places it inside what I can only assume is a running system...

I've spent the last week or so just trying to get this to work and I haven't been able to - I've even followed other articles outlining downloading different versions of libwidevinecdm.so from different repositories to paste into a running instance of Chromium OS with no results. I can only imagine that at this point I'm simply in way over my head when it comes to this as I can't imagine it being as difficult a thing to achieve as it seems...
