### ISSUE TITLE
sleep stops keyboard and touchpad from working

### ISSUE THREAD

**Issue by Mia-Gage** [arnoldthebat/chromiumos#187]
hi there so when i close my laptop lid it goes into sleep mode and when it wakes up from sleep the keyboard and touchpad dont work till reboot for some reason does anyone know why???   (i use sleep mode alot with laptops as its really handy so it would be helpful if someone could answer this pls     thx)

**Comment by arnoldthebat** [comment]
Can you try the R69 builds. They appear to be more stable.
