### ISSUE TITLE
RTL8188EU not working

### ISSUE THREAD

**Issue by ManasMalla** [arnoldthebat/chromiumos#189]
I am not able to use chromium os because as sons as i boot into it from usb it asks to connect to wifi, my wifi usb sv ( rtl8188eu) is not being detected. please fix this issue and please send me the link to the chromium os file after keeping the files for rtl8188eu 
my email id - learnwithsuperoreo@gmail.com
Waiting to use it
Kindly look after it quicky
Thanking you ,
Manas Malla

**Comment by yenon** [comment]
I'm having the same issue on my Acer Switch Alpha.

**Comment by arnoldthebat** [comment]
Should be fixed in R71. Please test and feedback

**Comment by ManasMalla** [comment]
Pls send link for r71

**Comment by yenon** [comment]
It's working as intended now, thanks for the fix!
