### ISSUE TITLE
Please let me know if you find a fix

### ISSUE THREAD

**Issue by clashy69** [arnoldthebat/chromiumos#193]
So I been trying to install this chromium os to hard drive so I can just boot up to chrome os without usb but I been trying to do this for a week now and every time I install and then turn off laptop and remove usb and then see if it installed, it just instantly sends me to UEFI of my laptop with no boot prioritie. pls help really want chrome os as default.

**Comment by arnoldthebat** [comment]
What laptop is it?

**Comment by clashy69** [comment]
Asus X501 with specs: Intel I3, graphics card HD4000 and 4 Gb ram is a potato ik

**Comment by arnoldthebat** [comment]
Im going to close this since its too old really and I have nothing to really work on to fix this...
