### ISSUE TITLE
Qualcomm Atheros QCA61x4A Wi-Fi doesn't work on R69

### ISSUE THREAD

**Issue by Adamentys** [arnoldthebat/chromiumos#201]
Hi,

I have an Acer Switch Alpha 12 with a Qualcomm Atheros QCA61x4A Wi-Fi card and Wi-Fi doesn't work on R69 Special.

I've tried CloudReady based on Chromium OS 68.4.59 and Wi-Fi work as it should, now trying with R67 Special.

**Comment by phant0m3rr0r** [comment]
Does using R67 solved the problem?

**Comment by phant0m3rr0r** [comment]
@Adamentys Does using R67 solved the problem?

**Comment by ilkersigirci** [comment]
I have samsung galaxy book 10.6 which uses the same wifi card.But my wifi doesn't work neither on CloudReady nor on Arnoldthebat version. It is interesting that your's works on CloudReady

**Comment by arnoldthebat** [comment]
Added in to R71 as part of ath10k fix,
