### ISSUE TITLE
Which is the last stable version? with Play Store running

### ISSUE THREAD

**Issue by ningacoding** [arnoldthebat/chromiumos#204]
i really need a chrome os version with play store running, even if is a very old version of the build. Please some one can share the link of the image?

**Comment by CalebQ42** [comment]
As per #179 it doesn't seem to be working on any builds, though it might be working on the next one. If you really need it then you can always try this: http://zzsethzz.blogspot.com/2015/09/install-chromium-upgrade-it-to-chrome.html  
I haven't in a while, but I have gotten it working successfully with Play Store support before.

**Comment by CalebQ42** [comment]
This is a list of devices with Play Store support, so if you install one of these builds you should have the Google Play Store. https://www.chromium.org/chromium-os/chrome-os-systems-supporting-android-apps

**Comment by ningacoding** [comment]
i gonna give a try and i comment the feedback

**Comment by ningacoding** [comment]
Hello, i tried all the ways, easy mode and manual mode, no success :(

**Comment by ningacoding** [comment]
After installing Arnold images, PC starts OK, Play Store still not working, then i patch with ChromeOS image and PC doesn't starts, i tried with 3 "similar" PC's recovery images.

**Comment by arnoldthebat** [comment]
None of my images support play store until Google open source the blobs... Sorry - nothing I can do about this
