### ISSUE TITLE
How to add overlay to TOT (R72)

### ISSUE THREAD

**Issue by AdamKearn** [arnoldthebat/chromiumos#211]
Hi,  I am trying to install this overlay but every time I try to build the packages I get errors.
I have opened a post on the chromiumos forum but every time I fix one problem I am getting a new error message and it is a forever loop.

Could you help me out and try and get this working.  Thanks.

[https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/Bog64rRMq08](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-os-dev/Bog64rRMq08)

**Comment by arnoldthebat** [comment]
Replied to your google groups. You really need to sync amd64-generic ToT to your overlay to stand a chance of it building
