### ISSUE TITLE
Realtek RTL8723B WLAN Driver

### ISSUE THREAD

**Issue by deovicchristian** [arnoldthebat/chromiumos#216]
Wifi is not recognized in Acer Z1402-50FZ which use Realtek RTL8723B

**Comment by arnoldthebat** [comment]
This 'might' be fixed for R71. Can you test when its available?

**Comment by deovicchristian** [comment]
can't wait :) please make it available sooner

**Comment by deovicchristian** [comment]
> This 'might' be fixed for R71. Can you test when its available?
can't wait :) please make it available sooner

**Comment by deovicchristian** [comment]
> This 'might' be fixed for R71. Can you test when its available?

can't wait, please make it avalable sooner

**Comment by Ghostfly** [comment]
Not fixed for me, using RTL8723 no Wifi (on a Lenovo 80NR)

Is there a way to load a driver manually to make some tests ?
