### ISSUE TITLE
Asus F55u with Realtek wifi card

### ISSUE THREAD

**Issue by bryanw20** [arnoldthebat/chromiumos#222]
Hi couldn't find any other was to ask questions.
I have an Asus F555u laptop (windows reports it as X555UA) that I suspect has a bad hdd control board (it randomly only boots to bios vs loading windows, other times it works just fine)

Anyway hoping to just use it as a Chromebook running off a usb drive 

Got Camd64OS-20181215 to load & run; but only via ethernet; can't find the wifi card.

Tried Camd64OS_R64B & Vanilla; both got as far as showing the wifi list, I pick mine, enter the password, then it just starts boot looping.

Windows says it's a realtek 8821AE wifi card
Intel core i7 6500

is there a better version I should be loading?

Also the touch pad seems sluggish & occasionally unresponsive.

thanks; if this isn't the right place to ask; please close this issue & point me in the right direction.

**Comment by arnoldthebat** [comment]
Additional realtek support is in the latest Alpha build. Please test and feedback
