### ISSUE TITLE
X1 Extreme does not wake up from sleep

### ISSUE THREAD

**Issue by samuelhautcoeur** [arnoldthebat/chromiumos#228]
Waking the computer up reboots it immediately (POST screen) on a Lenovo Thinkpad X1E (https://psref.lenovo.com/Product/ThinkPad/ThinkPad_X1_Extreme)

Tested with:
- Camd64OS_R72-11316.B-Special
- Camd64OS_R69-10895.B-Special

How can I provide useful logs?

**Comment by samuelhautcoeur** [comment]
Fixed in 73.03644.0 (https://chromium.arnoldthebat.co.uk/.testing//chromiumos_image.bin.gz)

**Comment by NanhuGITHUB** [comment]
Close the issue.
