### ISSUE TITLE
Update command  failed

### ISSUE THREAD

**Issue by sojab0on** [arnoldthebat/chromiumos#231]
Hi Arnold,

The Update command update_engine_client --update --omaha_url=http://chromebld.arnoldthebat.co.uk:9080/update ends in error kOmahaErrorinHTTPresponse(37)

sudo stateful_update just returns back unexpected end of file 3 times and than stops.

What can i do to fix the update release i have now Camd64OS_R69-10895.B-Vanilla.7z
There is an R72 build out but cant update to that.

**Comment by arnoldthebat** [comment]
The server only runs when Im happy to release the image to the wider audience. You can check the status http://status.arnoldthebat.co.uk/
