### ISSUE TITLE
RTL r8723bs not working 

### ISSUE THREAD

**Issue by onionknight502** [arnoldthebat/chromiumos#235]
HI

i have a nuvision tm800w560l tablet i tried to boot R72 Chromium but wifi not working in linux adding r8723bs solve the problem , i tried cloud ready and it works, could anybody please help me i realy need this tablet for taking notes but windows is carbage, linux not optimized for touch and android x86 buggy and half works.

*In cloud ready i check the loaded modules with lsmod and there is r8723bs.
And i would realy appreciate if someone can tell me how to add modules cause most of the stuff on tablet not working like sensors bluetooth power button.

thanks in advance 
moh.

**Comment by onionknight502** [comment]
Weirdly i just tested the R64 special and the wifi works, i will try to update it with my fast 50kbs internet and see if its keep working.

**Comment by arnoldthebat** [comment]
Please test in the latest alpha build and feedback. Hopefully this is fixed now
