### ISSUE TITLE
HP Stream 11 Touchpad fails on special builds

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#24]
HP Stream 11
Touchpad: Synaptics (According to windows)
Wireless: RTL8723BE

Results: When using the daily builds, EVERYTHING works (except wireless)
When using the special builds, Wireless works! — but touchpad no longer works… Tried the above steps, but it still isn’t recognized.

**Comment by Jonnyw2k** [comment]
Issue still present on r50-7881

**Comment by arnoldthebat** [comment]
Should now work
