### ISSUE TITLE
Qualcomm QCA61x4A not working on Special R72

### ISSUE THREAD

**Issue by filippghost** [arnoldthebat/chromiumos#240]
Forced to use an USB ethernet adapter, the WiFi just doesn't turn on. GalaxyBook 12

**Comment by HunterPlus** [comment]
For QCA9377 do this: 
type Ctrl + Alt + F2
$ cd /lib/firmware/ath10k/QCA9377/hw1.0
$ ls
board-2.bin  board.bin  firmware-5.bin  firmware-6.bin  notice_ath10k_firmware-5.txt  notice_ath10k_firmware-6.txt
$ sudo rm firmware-6.bin notice_ath10k_firmware-6.txt

So for QCA6174, $ cd /lib/firmware/ath10k/QCA6174, remove hw3.0, I think its OK, but I don't ensure.

**Comment by vannhi** [comment]
@HunterPlus Removing hw3.0 does not work. The kernel tries to look for firmware file in this folder.

**Comment by vannhi** [comment]
It seems it's the same issue as: https://ubuntuforums.org/showthread.php?t=2384640
Since, the wifi works with fyde, so I took the file lib/modules/4.14.83/kernel/drivers/net/wireless/ath/ath.ko from fyde image to replace the one in Special R72. It works now.

**Comment by arnoldthebat** [comment]
Should be sorted in later builds regardless. Please test.
