### ISSUE TITLE
RTL8188EU not working

### ISSUE THREAD

**Issue by ManasMalla** [arnoldthebat/chromiumos#245]
Please Bild chromium os that support rtl8188eu WiFi USB please and share the link
Best if chromium os 72

**Comment by ManasMalla** [comment]
Trello - email -learnwithsuperoreo@gmail.com

**Comment by arnoldthebat** [comment]
Should be working in the latest alpha build released today. Please test and feedback.

**Comment by arnoldthebat** [comment]
Should be working in the new Alpha build which Ill be releasing in the next few days. Please test and feedback.

**Comment by ManasMalla** [comment]
Ok so was the alpha build released?? If so please specify the build number!
