### ISSUE TITLE
Will Enterprise Enrollment work?

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#25]
Blog member asked: I am wondering what the deal is with enterprise enrollment on your Chromium builds. Will I be able to manage your devices in a Google Apps domain if I enroll them by pressing Ctrl + Alt + E during first login? The input command does in fact bring up enterprise enrollment, but I’m hesitant to use chrome licenses without knowing what you have to say about this particular approach. I’m interested in provisioning settings and apps and such for users from afar using the Chrome Device Management console.

**Comment by arnoldthebat** [comment]
Everything works as it should except that I am unable to complete the enterprise enrollment. I receive the “Oops network issue” message.

**Comment by herrniemand** [comment]
Enterprise enrolment will not work, as it is required certified `chrome os`, that is only shipped with certified hardware

**Comment by arnoldthebat** [comment]
From google groups: https://groups.google.com/a/chromium.org/d/msg/chromium-os-discuss/nVtb-FirGUI/-MSRYyxyHG4J

Looks like its possible

**Comment by arnoldthebat** [comment]
I believe lots of folks are using this successfully on later builds now...
