### ISSUE TITLE
BCM4312 is not workng in the latest special build for x86

### ISSUE THREAD

**Issue by frankja2** [arnoldthebat/chromiumos#275]
I have downloaded Cx86OS_R60-9592.B-Special.7z and wifi is not working. Switch in on but can't find any network. Is there any chance to get it working?

**Comment by shuffleznl** [comment]
Probably the dev's need a little more info than this to decide if there's "any chance" :)
BCM's have proven difficult to support, find more info over on T100TA forums: http://www.transformerforums.com/forum/asus-transformer-book-t100-alternate-os-s-development/
And specific topic on BCM with Linux: https://github.com/5bentz/linux-asus-t100/blob/master/T100TA_guide.md#enable-wifi

**Comment by arnoldthebat** [comment]
Its not likely I can fix this anytime soon, sorry!
