### ISSUE TITLE
Update servers' urls

### ISSUE THREAD

**Issue by pitsi** [arnoldthebat/chromiumos#280]
Dear maintainer.
How can I update an existing installation without installing it fresh from usb? I found these 2 guides at your site, but none works because all urls lead to a 404.

https://arnoldthebat.co.uk/wordpress/2012/12/28/dev-server-updates-now-available/
https://arnoldthebat.co.uk/wordpress/2014/05/10/dev-server-update/

I am on "CHROMIUMOS ENHANCED VANILLA BUILD – R74-11895.B" and I would like to update to the latest one without reinstalling.

**Comment by arnoldthebat** [comment]
The update servers only run occasionally. Just check http://status.arnoldthebat.co.uk/ to find out whether they are running or not...

**Comment by pitsi** [comment]
Thanks. I did not know about the status page.
However, when I try updating as you suggest, via the browser, I get a "your chrome device is updated" massage. Am I doing something wrong?
