### ISSUE TITLE
The sound and touchpad do not work. HP Chromebook 11 G4

### ISSUE THREAD

**Issue by TheEcki** [arnoldthebat/chromiumos#285]
Hello, I have a problem with the sound. Probably no drivers for the sound card, the card model is byt-max98090. The touchpad freezes and sometimes the right-hand control does not respond to touch commands. He stands still.
Touchpad model: Elan Touchpad as / devices / platform / 80860F41: 00 / i2c-0 / i2c-ELAN0000: 00 / input / input5

**Comment by shuffleznl** [comment]
Hi @TheEcki,
This device has official ChromeOS release, based on Kip: https://cros-updates-serving.appspot.com/
R75 is available (newer than latest ATB Special R74). I assume Sound and Trackpad works in there.

**Comment by TheEcki** [comment]
Hi @shuffleznl,
I wanted to install chromefy because my Chromebook doesn't support Android apps. I need a working version of Chromium OS with all the drivers on my Chromebook.

**Comment by shuffleznl** [comment]
Try Chromefy with Kip as Recovery.

**Comment by arnoldthebat** [comment]
Should be fixed as part of the latest Alpha build that I will release in the next few days.
