### ISSUE TITLE
Broadcom WL doesn't support BCM43241

### ISSUE THREAD

**Issue by pyover180** [arnoldthebat/chromiumos#287]
I own a ThinkPad 10, which uses BCM43241 rev 5 (combo WiFi, Bluetooth, FM). Wireless chip is not detected at all by any sort of ls functions.

Broadcom proprietary doesn't support this combo chip. I can compile 4.14.109 for Debian to retrieve brcmfmac and brcmsmac. Can you please keep the .ko in the /lib/modules/drivers/... folder and leave specific instructions for other users with similar hardware configurations? Theoretically it's insmod, copy NVRAM, modprobe, profit.

Again, I must stress that I don't have the option of simply installing a new wireless card. It's SDIO, and soldered on to a single board.

**Comment by shuffleznl** [comment]
Some folks over at the Asus T100 community have been working on this a while. T100 also has SDIO 43241: http://www.transformerforums.com/forum/asus-transformer-book-t100-alternate-os-s-development/

Here's direct link: https://github.com/jfwells/linux-asus-t100ta/blob/master/nvram/lib/firmware/brcm/brcmfmac43241b4-sdio.txt

**Comment by arnoldthebat** [comment]
Should be supported now in the new alpha builds: https://arnoldthebat.co.uk/wordpress/2019/09/08/alpha-builds-r78-12476-0-2019_09_08/ 

Can you test and feedback please?

https://wireless.wiki.kernel.org/en/users/Drivers/brcm80211 for additional details
