### ISSUE TITLE
Realtek 8821CE Wireless not working.

### ISSUE THREAD

**Issue by LHesiquio** [arnoldthebat/chromiumos#294]
There is a problem with this wifi card, because it fails to boot during ChromiumOS boot.

On the other hand, do not know how they work, if with official drivers, or simply implement drivers created by the community, like these.

i have two links for this driver, but i don't know how i can implement to the kernel

1.- https://github.com/endlessm/linux/tree/master/drivers/net/wireless/rtl8821c
2.- https://github.com/tomaspinho/rtl8821ce

**Comment by minaki76** [comment]
Hi, I have the same problem too :(  and I haven't found any working solution:((

**Comment by arnoldthebat** [comment]
Try the latest alpha build please and let me know if it works. If not, post the output of dmesg and lsmod

Thanks

**Comment by arnoldthebat** [comment]
Closed awaiting testing feedback.

**Comment by minaki76** [comment]
Hi,

Everything works well :)
Thanks

Michał Nakielski




czw., 28 lis 2019 o 13:57 arnoldthebat <notifications@github.com>
napisał(a):
