### ISSUE TITLE
Realtec 8187se not working

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#3]

**Comment by Laurent68** [comment]
Hi Mr. Batman,

Have an old (really old) LG X110, where I countless times have tried to install a version chromium OS to see what it is all about. Recently I tried CHROMIUMOS SPECIAL BUILD – R55-8777. This almost made it. Never have I been so far in the process of installing the OS. Alas, the network didn't work :-(
Apparently, the WiFi card in the LG X110 is a RT 8187se, so now I know why :-)
Any chance this will be fixed? The notebook is so small, nice and cute, and you cannot see it has been used, so I'd love to have it do 'something'...

Rgds
Christian

**Comment by arnoldthebat** [comment]
Try the latest R64 build please. This should now have support.
