### ISSUE TITLE
question - docs for board porting

### ISSUE THREAD

**Issue by cjbd** [arnoldthebat/chromiumos#342]
hello, awesome project!

i'm learning to create my own overlay, but i haven't found enough documents to start with, i only have [official porting guide](https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/chromiumos-board-porting-guide)

can you please give me some pointers, thank you!

**Comment by arnoldthebat** [comment]
Start by following the main development guide, on the amd64-generic board.

Then start to tailor that to suit, and clone it when you are ready to create your own overlay.
