### ISSUE TITLE
Intel GMA3600 not working

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#35]
I get an error “trying to get vblank count for empty pipe 0”. The boot process stops there and hangs.

**Comment by arnoldthebat** [comment]
Possibly related? http://www.linuxquestions.org/questions/slackware-installation-40/black-screen-on-intel-desktopboard-d2500cc-4175503983/ for review?

**Comment by dmpanch** [comment]
The same for me, but I don't see any messages at all. Just black screen after trying to boot.

**Comment by arnoldthebat** [comment]
X is no longer supported. Closing
