### ISSUE TITLE
Intel GMA 3100 not working

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#38]
Kernel Panic with 

EIP [<8a2b165b>] intel_parse_bios+0x632x1064 SS:0068:be83bd38
Kernel panic – not syncing? Attempted to kill init! exit code=0x00000009

**Comment by ili-codes** [comment]
Latest special build 64bit worked on my Thinkpad T61 with GMA X3100. Was stuck on "please wait" though.

**Comment by arnoldthebat** [comment]
X is no longer supported. Closing
