### ISSUE TITLE
rtl8723be broken on C*OS_R47-7451

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#39]
Before Sep 14 , 2015 . I can’t use your daily or weekly build version , because my rtl8723be wireless network-card don’t work in it . Only your special build version (such as “Camd64OS_R46-7323.0-Special”) let my rtl8723be work well .

But now , i lost my last hope :) because my rtl8723be don’t work in your latest special build version that “Camd64OS_R47-7451.0-Special” .

When i type “lsmod | grep rtl8723be” , i get :

rtl8723be 65326 0
btcoexist 35588 1 rtl8723be
rtl8723_common 17963 1 rtl8723be
rtl_pci 24808 1 rtl8723be
rtlwifi 52809 2 rtl_pci,rtl8723be
mac80211 425170 3 rtl_pci,rtlwifi,rtl8723be

We can see the module is already loaded , maybe has some change in the latest special build version that make any problem .

**Comment by LarsNorgaard** [comment]
Seems like a lot of the 8723 cards wont work at the moment.
I have the 8723BS myself, and can't get it to work.

I don't know if this would help you:
https://github.com/lwfinger/rtlwifi_new
*#This code will build on any kernel 3.0 and newer::*

**Comment by arnoldthebat** [comment]
Thanks for that, Ill look to include for the next build

**Comment by ThomasJSVos** [comment]
@arnoldthebat Is there any way to get this to work? It doesn't work on the latest special build.

**Comment by arnoldthebat** [comment]
Looking at it as soon as I can,

**Comment by ewigg** [comment]
@arnoldthebat Is the rtl8723be card supported in any build. Tried the latest with my HP Stream 13 with rtl8723be but it wont work.

**Comment by arnoldthebat** [comment]
Should be fixed in the latest R64 build. Please test and feedback
