### ISSUE TITLE
ARC/Android Apps Stuck at logo

### ISSUE THREAD

**Issue by rafi16jan** [arnoldthebat/chromiumos#42]
Don't know how to find the log, but it's impossible to run android apps, stuck at logo.

**Comment by farrell16jan** [comment]
![screenshot 2015-09-22 at 13 13 36](https://cloud.githubusercontent.com/assets/7939687/10011911/c88b8aa8-612b-11e5-8c00-6fa2dcb5f4e1.png)

**Comment by mpipo** [comment]
I'm getting something like this too. Logs point into the direction of kernel misconfiguration (IIRC /proc related)

**Comment by arnoldthebat** [comment]
Could you get me a copy of the logs?

**Comment by mpipo** [comment]
Sorry Arnold, somehow the error changed (and way less verbose) this is all I've got.

ChildPlugin backgroundpage:0:umareporter(so_executable) Run: 16001.780ms
child_plugin.js:326 timeout to spawn ChildPlugin process: umareporter(so_executable), umareporter bool ArcRuntime.DexoptInterrupted false
child_plugin.js:202 retry to spawn with timeout 32sec.
main.html:1 NativeClient: Nexe crashed during startup

I'll see what I can do.

**Comment by mpipo** [comment]
The problem is even worse than what I initially thought: Everything using NaCl isn't working. Guess I'll file a new bug report.

**Comment by ili-codes** [comment]
Hmm, this may be the thread I'm looking for. I downloaded VLC from the Chrome Web Store (latest special build, 64bit) and it's stuck on the logo. Left it for 30min and it's stuck on the logo.

**Comment by Coburn** [comment]
The biggest problem with ARC or Android apps is that so many of them use the Google Play runtime. But there is no way to install it as a "dependency" of the app. This may have changed since last year when I looked at it, but you would think that two Google products could be integrated free of charge. Hope somebody's working on that.

**Comment by arnoldthebat** [comment]
ARC whilst enabled will not work until google supply the blobs under open source.
