### ISSUE TITLE
Dell GX 520 sound card drivers to add?

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#43]

**Comment by arnoldthebat** [comment]
Analog Devices 198x Integrated Audio Driver

**Comment by happyclayton** [comment]
This is an issue for me also. Is there anything I can do to help get this driver into the build? (I am a competent Linux user, but have done little compilation / building.)

**Comment by arnoldthebat** [comment]
Should be sorted in the latest build on ChromiumOS version 54xx. Tested on loan machine working as expected
