### ISSUE TITLE
Broadcom BCM4311 not loading

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#47]
![image](https://cloud.githubusercontent.com/assets/3314969/10952281/d46a4d52-8339-11e5-932f-8090b96fd98f.png)

**Comment by ComputeLinux** [comment]
plox fix cannot use meh looptop wefi

**Comment by ComputeLinux** [comment]
Seriously. It's been over a year, this hasn't been fixed.
I'm trying to figure out why, but it's really annoying.

**Comment by Tsaukpaetra** [comment]
@ComputeLinux  probably because I think there's literally only one guy working on this.

**Comment by arnoldthebat** [comment]
Wont fix. If the broadcom sta drivers doesnt fix, folks will need to go and buy a intel wifi card.
