### ISSUE TITLE
Import CA certificates not possible

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#48]
I’ve had issues trying to import CA certificates (greyed out on all buttons for import) via https://support.untangle.com/hc/en-us/articles/202376838-Installing-Root-Certificates-on-Chromebooks-

**Comment by mrscottmoree** [comment]
I have noticed the same issue, all buttons are greyed out. Camd64OS_R48-7549.0.U-Special

**Comment by helpdeskdan** [comment]
Still present in CHROMIUMOS SPECIAL BUILD – R50-7881.  That said, this latest build has fixed some other issues I was having.

**Comment by juanquy25** [comment]
Is there an ETA on the resolution for this issue? I work for a school district and this is the only thing preventing us from from being able to use a bunch of old laptops. Thanks in advance.

**Comment by helpdeskdan** [comment]
For wireless, is possible with command line.

**Comment by juanquy25** [comment]
could you share with me the commands you used? I don't have an issue with wireless but I do with adding a network filter's certificate. thanks in advance.

**Comment by helpdeskdan** [comment]
With wireless, wpa_supplicant can be run from command line combined with other linux commands.  However, for your issue, try certutil and let me know if it works.  For more info: http://www.korecky.org/?p=855

**Comment by arnoldthebat** [comment]
Also review: https://www.chromium.org/developers/design-documents/tpm-usage

**Comment by arnoldthebat** [comment]
I now know the cause - a lack of TPM support. On newer laptops, simply enabling TPM in bios (with no additional config) allows the UI to work and presents a set of default certs. Ill be looking to build in a TPM emulator therefore for older models

**Comment by baude** [comment]
Thats great news @arnoldthebat .  Im happy to test as well.

**Comment by baude** [comment]
Any news @arnoldthebat  ?

**Comment by arnoldthebat** [comment]
@baude none as yet. Still hacking around trying to get it working. I think the tpm2 'should' allow this to work, but I need to understand it better...
