### ISSUE TITLE
rtl8192eu needs adding to wireless drivers

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#52]

**Comment by nebulakl** [comment]
Please add rtl8723au as well.
Thanks.

**Comment by arnoldthebat** [comment]
And RTL8191SU

**Comment by shawnskeown** [comment]
Not sure if this is helpful or not but found this: https://github.com/Mange/rtl8192eu-linux-driver

**Comment by flyover** [comment]
on a Gateway ZX6961 AIO
$ lsusb
Bus 002 Device 006: ID 0bda:8172 Realtek Semiconductor Corp. RTL8191SU 802.11n WLAN Adapter
