### ISSUE TITLE
Investigate Fake PAE for Pentium class machines

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#54]
https://help.ubuntu.com/community/InstalledSystemFakePAE

**Comment by arnoldthebat** [comment]
I’d like to make a case for working on Pentium-M support and that case is this: There are more business-class laptops out there of this caliber than you can possibly imagine still coming in to recycling companies all over the country. Quite literally thousands each day. Their parts are abundant and so are the materials that go into them. The dell D600, D610, D500, D505, D510, D800, D810. . .and IBM’s T41, T42, T43, R50, R51, R52. . .just to name a few of the most common. With the commercial good will behind the chromeos name, there is real viability in the refurbishing and reuse of these machines that are otherwise doorstops at best. It seems like such a shame to me that these machines can’t continue to be used and what you’re working on could allow for that. I won’t even go into the environmental impact of all of these machines becoming obsolete. The volume of machines built and sold in that area was at the literal PEAK of desktop and laptop sales, and they’re just gonna keep coming.

SO, that said, here’s the technical DL and what I’ve found in the way of solutions (or at least, moving toward one). If you have the time, your expertise in this domain would be profoundly appreciated.

NOW, onto the technical side: The first is PAE. The second is SSE2 support. Last things first, I’ve found a patch here: https://github.com/graysky2/chromium-no-sse2-patch to produce a version sans SSE2.
This one first because the solution is more closely related to this branch than what I’ve found for PAE.

As far as PAE, MOST of the Pentium Ms HAVE PAE but lack the flag for it so the kernel won’t recognize it. There appear to be numerous solutions to this out there, but not a whole lot of people with those solutions have a distro, much less one so relevant as what you’re producing. SO, any chance you might consider working on a ‘special’ build to include these as well?

**Comment by projectblack** [comment]
Have You Had Any Luck Because I Would Love To Install On Old Laptops I Have?

**Comment by tompoch** [comment]
seems like there is kernel option "forcepae" as suggested here: http://askubuntu.com/questions/117744/how-can-i-install-on-a-non-pae-cpu-error-kernel-requires-features-not-present/117751#117751 

hope it is not Ubuntu specific

**Comment by projectblack** [comment]
okay so how could i get that to work with chromium

**Comment by pjpreilly** [comment]
I have a machine to test on if anybody has any ideas.
