### ISSUE TITLE
Build support for RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#61]

**Comment by arnoldthebat** [comment]
Review https://unixblogger.wordpress.com/2011/10/18/the-pain-of-an-realtek-rtl8111rtl8168-ethernet-card/

**Comment by nscreated** [comment]
Issues appears to be resolved in Special Build R52-8268

**Comment by arnoldthebat** [comment]
Reported as fixed.
