### ISSUE TITLE
tap to click not working

### ISSUE THREAD

**Issue by Andy2244** [arnoldthebat/chromiumos#62]
Tap to click did not work for me on my synaptics touchpad, using the latest specialty build (02/2016).

Works fine using [www.neverware.com](url) ChromeOS builds.

**Comment by dryamJS** [comment]
If type in shell "synclient TapButton1=1" tap works. =) Now I trying to write a conf file

**Comment by dryamJS** [comment]
https://gist.github.com/dryamJS/a1542673b2fd9d946ae209930c86bb31
https://gist.github.com/dryamJS/b2629a0352aa5458a23417a217d5b1f6
https://gist.github.com/dryamJS/1a41d1b3a0629ca17a2cc86d453b9277

Now tap to click works fine. I shall write script later.

**Comment by Andy2244** [comment]
thx
