### ISSUE TITLE
Special Build patchset/repo?  Thinkpad X220 crouton and xorg

### ISSUE THREAD

**Issue by yebyen** [arnoldthebat/chromiumos#64]
Hello, I was going to see if I could get both freon and wifi on my Thinkpad x220, but I couldn't find any sources for the Special Build.  Did I just miss the link somewhere?  Is it maintained as a work-in-progress repo, or as a patchset that you can apply to a point in time snapshot of the chromium dev repo?  I had my fingers crossed that there was freon support for Intel graphics in the daily builds, and I could just patch in linux-firmware and build+install and cross my fingers...

If there were any instructions that you've compiled to describe the tags or SHAs to checkout from the official repo, and process of turning chromium mainline into your blessed Special Build, so I can cherry pick the parts I need and build my own, that would be awesome and I'd appreciate the link.  If there wasn't... any advice?  Where would you suggest I begin?

I'm trying to get Crouton + Freon + xorg target working.  I haven't been following any other chromium dev news, so I don't know if freon support is work-in-progress or otherwise even started.  Do you know if there is another way to use crouton?  I know it didn't always require freon (there was crouton with xorg target before there was freon at all...)

**Comment by ili-codes** [comment]
I've got a ThinkPad x230i with the Special build (latest) working, but no crouton/xorg for me either. Tried `startx` and `startxfce4` to no avail.
