### ISSUE TITLE
Intel Wireless 3165 not working

### ISSUE THREAD

**Issue by redkill3r42604** [arnoldthebat/chromiumos#66]
Intel Wireless 3165 not working on Chromium OS, meaning no WiFi is detected. WiFi works on other Linux Distros that use Linux Kernel 4.2 and newer.

**Comment by redkill3r42604** [comment]
EDIT: I meant to say that WiFi works on other Linux Distros that use Linux Kernel 4.2 and newer.

**Comment by tvman-123** [comment]
I second this issue

**Comment by redkill3r42604** [comment]
WiFi works on x86 version of the Chromium OS daily builds, but my eMMC (Hynix HGB4e) is not found, so I cannot install onto hard drive (or eMMC in my case). My eMMC path is "/dev/mmcblk0". eMMC is found on x64 version of the Chromium OS daily builds, but WiFi doesn't work. Screen is blank on x64 version of Chromium OS Special Builds.
