### ISSUE TITLE
No MP4 or MP3 support on my Thinkpad X230i

### ISSUE THREAD

**Issue by ili-codes** [arnoldthebat/chromiumos#67]
I am using the latest 64bit special build on my ThinkPad X230i and got flash working fine (with the brash.ca script) but sadly Mp3 and Mp4 does not work! How come and how to get it working?

**Comment by arnoldthebat** [comment]
Mp3 and MP4 are now working in the latest special builds

**Comment by ili-codes** [comment]
Thanks!
