### ISSUE TITLE
Screen flackering ATI radion / HP Compaq 6715s

### ISSUE THREAD

**Issue by chackr** [arnoldthebat/chromiumos#68]
My screen keeps flackering on this very old Notebook with the special build, what can I do?

**Comment by jansenpd** [comment]
I have the same problem with an old Acer Aspire 5532, with ATI Radeon HD3200 Graphics. I've tried your newest version (Nov 20, 2016) and the oldest archived that you still have up (May 29, 2016). A page at https://bugs.chromium.org/p/chromium/issues/detail?id=352933 shows that many with Acers have had this problem, and said that an old build, Cx86OS-20140617010101.img.7z, fixed it for them. Is it possible to get a link for this two year old version to see if it would work?
