### ISSUE TITLE
Build Support for Intel AC 3160 

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#72]

**Comment by 1823alex** [comment]
Any updates on this? Trying to get my 14" IdeaPad 100S working, I can boot to the latest build and am able to see Wifi networks near me, I go to connect to one and put the password in but after that it doesn't connect to the network and no networks are shown at all, and there is something saying Enable Wifi which is grayed out.

**Comment by arnoldthebat** [comment]
@1823alex can you try the special builds? They have wifi manager disabled which fixes the problem you note with networks disappearing

**Comment by 1823alex** [comment]
I've tried the special builds and they didn't allow any network connection
as well or they didn't boot up properly.
