### ISSUE TITLE
Review sleep states

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#75]
Not sleeping correclty on Asus Zenbook UX305FA (Intel Core m processor).

Asus Zenbook UX305FA (Intel Core m processor).

It boots fine. I need the special build to get wifi, bluetooth is untested. I was able to get it running and get a really good feel for Chromium OS and see what I can do with it. However, the one thing that prevents me from leaving it on the laptop is it can’t sleep.

When I close the laptop, it attempts sleep, but never seems to completely go into sleep state. As a result, it gets into an unusable state and appears dead. I have to power cycle the laptop to get it running again. This actually makes Chromium OS unusable for me as this will require that I shut down even if I just want to close the lid while plugged in. In Windows and Linux, I generally have the lid close while plugged in “do nothing” but there are no configurations for this in Chromium OS that I’ve found.

**Comment by cffm** [comment]
On my Lenovo W500 it is similar but a bit different. It goes to sleep when I close the lid but it never goes to sleep when it is on ac. Timeout switches of the display but the laptop would run for all eternity...  log file (powerd) reveals it is not even trying. It appears to me that it did not set a timeout (and therefore doesn't call it?).

**Comment by Nimdae** [comment]
It was recommended in the comments where this defect originates from to try an older build as sleep states apparently worked previously. I tried the r50 based build and it did not boot at all on the UX305FA.

Looking forward to testing anything that comes along to help get this fixed.

**Comment by Nimdae** [comment]
I've done some experimentation.

The build hosted at http://chromeos.hexxeh.net/ will sleep and wake up, but after sleep and wake up, it becomes unstable. It will work for a short while then crash. Unfortunately I can't do much debugging on that build. Also, they do not have an open group for troubleshooting/bug reporting.

The latest nightly here will boot on my laptop and I actually get wifi now. However, sleep still fails. It appears to attempt to sleep but never completely enters sleep and is unrecoverable.

If there's anything I can provide you to push this further, I'm open.

**Comment by edcunningham** [comment]
R54 Special Build on Acer Chromebook c720p, also having sleep issues as described by the first commenter.

(It's a chromebook but running coolstar.org's UEFI firmware, to turn it into a standard intel laptop. No problems with Windows or Xubuntu so it seems to be a chromiumos associated issue.)

Sleep problems are intermittent--closing the lid and later reopening it results in it working fine about 10% of the time, but most of the time the screen just stays black requiring a hard reset. I don't really know where to start in troubleshooting this, but if there's any logs or such I can get you i'll be happy to help.
