### ISSUE TITLE
Build Support for AMD Radeon 7340 Integrated Card

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#76]

**Comment by NiggerKiller420** [comment]
Heya bud. I've run into that problem within the same line of graphics cards. Not the 7340, The Radeon HD 6310 internal card. 
Cheers.

**Comment by asrsmunna** [comment]
Same issue, a blank screen after Chromium OS screen.
Processor: AMD E2-1800 APU with Radeon(tm) HD Graphics
Video Card: AMD Radeon HD 7400M Series

**Comment by Donenz** [comment]
Is there an image or solution for this? I am having the same issue

Thanks
