### ISSUE TITLE
xorg: no screens found

### ISSUE THREAD

**Issue by keydon** [arnoldthebat/chromiumos#77]
hello there,

i am trying to boot your builds from USB, but i am stuck at "kernel is booting".

Release: Camd64OS_R52-8268.0-Special
Logs from chromiumos:
- xorg http://pastebin.com/BpLL4EES
- dmesg http://pastebin.com/KKdHGxY1

Logs from ubuntu/mint:
- xorg http://pastebin.com/g8kz9zhS
- dmesg http://pastebin.com/8NT8AEK9
- lsusb http://pastebin.com/SdMNRfVf
- lspci http://pastebin.com/MCSxVRj8

Any ideas whats wrong and how to fix it?

Best regards,
keydon

**Comment by keydon** [comment]
yea sure, just close it.

**Comment by arnoldthebat** [comment]
Well seeing how chromium os doesn't have X at all anymore, I thought it wise....

**Comment by keydon** [comment]
well thanks for that valuable information. so i guess i could give it another try?

**Comment by arnoldthebat** [comment]
Feel free. Intel should be fine. nVidia is doomed. Radeon is 50/50
