### ISSUE TITLE
Intel i915 hangs

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#79]
http://pastebin.com/3w5f9sHp

[drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.

**Comment by arnoldthebat** [comment]
GPU Crash Dump
http://pastebin.com/NHQ9nPVR

**Comment by lavjamanxd** [comment]
I have this problem too, but there is a solution for that (if im right this is the same which affects my netbook)

if you add intel_idle.max_cstate=1 as a kernel parameter in the grub config, then it will work fine without freezes
