### ISSUE TITLE
No Sound on Atom boards Atom Processor Z36xxx/Z37xxx

### ISSUE THREAD

**Issue by arnoldthebat** [arnoldthebat/chromiumos#81]
http://pastebin.com/0kQmhPY6

00:1b.0 Audio device: Intel Corporation Atom Processor Z36xxx/Z37xxx Series High Definition Audio Controller (rev 0e)

**Comment by Ludoboii** [comment]
Is this bug ever going to be fixed? Was it already fixed? I'm asking because there's no sound on my Mediacom Winpad W911, which has an Intel Atom Z3735F, and I wonder if it's because of the processor or if there's another reason.
