### ISSUE TITLE
AMD E-450 17" boot only cursor and black screen. 

### ISSUE THREAD

**Issue by indyend** [arnoldthebat/chromiumos#82]
I'm write Chrome OS to USB. When chromium os show up and i get black screen with cursor, i can shutdown with invisible's bottom at the left corner of screen.

PS. Sorry for my weak ENG.

**Comment by ElijahUSA** [comment]
Same situation

**Comment by gsaksena** [comment]
Same issue on a core2 duo E6850 desktop.

**Comment by pbiswal** [comment]
I too have the same issue on Asus x55u laptop.
