### ISSUE TITLE
romanian keyboard

### ISSUE THREAD

**Issue by criptoriga** [arnoldthebat/chromiumos#83]
Hello. I'd like to use ChromiumOS as a productivity machine, but I need romanian layouts in my keyboard (the winkeys variant, if possible). Is there any chance that I could get it?
Thnaks.

**Comment by AlexMasterRO** [comment]
Salut! Incearca sa gasesti o aplicatie/extensie pe chrome store pentru tastatura in romana.

**Comment by arnoldthebat** [comment]
looks to be supported in R64 onwards
