### ISSUE TITLE
Enrolment with Developer Build version?

### ISSUE THREAD

**Issue by cleader24** [arnoldthebat/chromiumos#86]
Posted this on the main blog page, but realised it should probably be here instead..!

Hi,

Trying out your latest build on a few old netbooks for a new school deployment. We’ve found that v52-8268 seems to load OK but have stumbled at the hurdle of Enrolling. We’re getting a message to the effect of “Device is locked in a mode that prevents enterprise enrolment”

Other new ‘real’ Chromebooks are enrolling fine, and end up being fully policy-controlled, so although it’s a relatively new backend, it’s definitely working fine. Just wondering whether there’s an issue with the build or with our backend settings..

Chrome About shows:
Version 52.0.27220
Platform 8268.0.2016_05_16_2144 (Developer Build – tonyd) developer-build x86-atb

Wondering whether it’s something to do with it being a ‘developer build’..?

Screenshot attached..

![20160728_182721](https://cloud.githubusercontent.com/assets/20744815/17272536/d89270fa-5690-11e6-9d37-51c4af8a824a.jpg)

Cheers – and thanks for the great work on the project so far!

**Comment by cagatay-y** [comment]
Do you use the special builds or daily/weekly builds? Special builds add support for enterprise enrollment. For more info about differences between special and daily/weekly builds, you can look [http://arnoldthebat.co.uk/wordpress/chromiumos-special-builds/](url)

**Comment by arnoldthebat** [comment]
Closing - its too old and things have moved on a tad. Specials only supported with Ent Enrollment
