### ISSUE TITLE
How to appy the option "Restrict Login to the Following Users" for a specific domain users

### ISSUE THREAD

**Issue by NelsonTeixeira** [arnoldthebat/chromiumos#88]
I need to turn on the option "Restrict Login to the Following Users" for a every students domain, as called (*@a.colegioser.com), but the chromium os does not allow to include them. When I insert a user account from this domain (@a.colegioser.com), the account is not added at the list of the users accounts.

**Comment by arnoldthebat** [comment]
I have no idea what this is sorry. Ill close for now since this is ancient so please reopen if its an issue.
