### ISSUE TITLE
Dell D620/D630 touchpad not working

### ISSUE THREAD

**Issue by chrisgerman** [arnoldthebat/chromiumos#89]
The Dell D620/D630 touchpad with Speical (32/64) are not working, but the Pointing stick works. Even after a stateful_update.

lspci: http://pastebin.com/Cvd7bkSs

lsusb: http://pastebin.com/1JZZwdVf

dmesg: http://pastebin.com/KfPjXwQB

**Comment by chrisgerman** [comment]
Nevermind, found the fix on your website but was hard to find. Here is the link:

http://arnoldthebat.co.uk/wordpress/2013/01/08/how-to-get-the-touch-pad-working-in-chromium-os/

On other note, would it be easy to have it installed already?

**Comment by arnoldthebat** [comment]
Wont fix. Superceded by fix in Vanilla builds
