### ISSUE TITLE
Radeon Graphics Not Booting Successfully

### ISSUE THREAD

**Issue by calvinmorrow** [arnoldthebat/chromiumos#90]
Booted R54 special amd64 with Radeon and only get a black screen. Alt-F2 works to access the developer console.

dmesg: http://pastebin.com/U1WpNM4M
Xorg: http://pastebin.com/ywB2K8DV

(Note:  I replied to the discussion in the latest Wordpress article but I've been stuck under awaiting moderation)

**Comment by arnoldthebat** [comment]
Radeon support should be much improved in the latest versions.
