### ISSUE TITLE
Touchpad not working on Acer Aspire E5-573-54ZV

### ISSUE THREAD

**Issue by anexoluiz** [arnoldthebat/chromiumos#91]
When i start chrome os the Keyboard is detected but the Trackpad is not, what i can do to fix that issue?
PS. Sorry for bad english.

**Comment by Wicho280** [comment]
This may help!

http://arnoldthebat.co.uk/wordpress/2013/01/08/how-to-get-the-touch-pad-working-in-chromium-os/

**Comment by arnoldthebat** [comment]
Possibly solved in latest Alpha build. Please test.
