### ISSUE TITLE
Enterprise Enrollment

### ISSUE THREAD

**Issue by kenbernhagen** [arnoldthebat/chromiumos#92]
Using Camd64OS_R54-8659.0-Special.7z
Installed onto hard drive
Go to enrollment screen enter administrator username and password receive Error "Oops! The system failed to establish the device installation-time attributes lock."
First time trying to install chromium and get it enrolled.  Please let me know if there are any steps that I am missing.

**Comment by niekt** [comment]
I have the same issue.

**Comment by arnoldthebat** [comment]
You need to have TPM enabled for this to work.... Apologies for the epic time to respond to this!
