### ISSUE TITLE
Qualcomm Atheros QCNFA435 Wifi Chip Support

### ISSUE THREAD

**Issue by PMARINA** [arnoldthebat/chromiumos#93]
Hey,
I'm currently using a lenovo flex 3: 80R3. I wanted to use your chromium os; however, when I load it, it does not recognize my wifi chip (internal). Please add support for this chipset. It would be much appreciated as my windows os has too much bloatware and eats too much battery. If it helps: I attempted to use linux distros a while back, but they also didn't recognize the chipset. When you finish, could you please email bluerat33@gmail.com. Thanks mate.

PMARINA

**Comment by arnoldthebat** [comment]
Can you try the latest builds please? They have the full Atheros FW stack deployed now
