### ISSUE TITLE
Widevine support

### ISSUE THREAD

**Issue by wcomartin** [arnoldthebat/chromiumos#99]
Have you given any thought about creating a special build with Widevine support for HTML5 DRM (this is needed for netflix)

https://bugs.chromium.org/p/chromium/issues/detail?id=429452#c16

Or.. is there another way of getting this to work that i am unaware of?

**Comment by SpaneBoswell** [comment]
I have heard of scripts that install Widevine but none of them worked for me. How about you?
And yes, this is really annoying. I am pretty sure it also effects music.google.com. However, it may be a flash issue.

**Comment by arnoldthebat** [comment]
Ill be deploying https://packages.gentoo.org/categories/www-plugins in the next version.....

**Comment by duckunix** [comment]
Which version is that?  I am using Camd64OS_R62-9901.B-Special, which is brilliant in every other way so far, but Netflix.
